name: Custom Github Checkout action
description: Checkout repository using Python script

inputs:
  repository:
    required: false
  ref:
    required: false
  token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Run checkout script
      run: python -u ${{github.action_path}}/main.py
      shell: bash