name: Build Pipeline

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SONAR_TOKEN:
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ${{inputs.service_path}}
          args: >
            -Dsonar.projectKey=devops-microservices-lab
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: ${{secrets.SONAR_HOST_URL}}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        with:
          scanMetaDataReportFile: ${{inputs.service_path}}/.scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}

      - name: npm audit
        run: |
          cd ${{inputs.service_path}}
          npm install
          npm audit --audit-level=high || true

      - name: Generate image tag
        id: tag
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      
      - name: Build and Push Docker Image
        uses: vardhan556/shared-github-actions/.github/actions/docker-build-action@main
        with:
          service_name: ${{inputs.service_name}}
          service_path: ${{inputs.service_path}}
          docker_username: ${{secrets.DOCKER_USERNAME}}
          docker_token: ${{secrets.DOCKER_TOKEN}}
          image_tag: ${{steps.tag.outputs.tag}}
      
      - name: Done
        run: echo "Pipeline completed successfully!!!"
