name: Build Pipeline

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string

    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
      SONAR_TOKEN:
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ✅ Start SonarQube container
      - name: Start SonarQube
        run: |
          docker run -d --name sonarqube -p 9000:9000 sonarqube:lts-community
          echo "Waiting for SonarQube to start..."
          sleep 30

      # ✅ Wait until SonarQube is ready
      - name: Wait for SonarQube
        run: |
          until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do
            echo "Waiting..."
            sleep 5
          done

      # ✅ Sonar Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ${{ inputs.service_path }}
          args: >
            -Dsonar.projectKey=devops-microservices-lab
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.login=admin
            -Dsonar.password=admin
            - name: npm audit
              run: |
                cd ${{inputs.service_path}}
                npm install
                npm audit --audit-level=high || true

      - name: Generate image tag
        id: tag
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
      
      - name: Build and Push Docker Image
        uses: vardhan556/shared-github-actions/.github/actions/docker-build-action@main
        with:
          service_name: ${{inputs.service_name}}
          service_path: ${{inputs.service_path}}
          docker_username: ${{secrets.DOCKER_USERNAME}}
          docker_token: ${{secrets.DOCKER_TOKEN}}
          image_tag: ${{steps.tag.outputs.tag}}

      # ✅ 7. Trivy Scan (Container Security)
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.service_name }}:${{ steps.tag.outputs.tag }}
          format: table
          exit-code: 0   # change to 1 later for strict security
      
      - name: Done
        run: echo "Pipeline completed successfully!!!"
